name: Automação Rewards

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite

jobs:
  run_bots:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install selenium random-word

    - name: Baixar e instalar WebDriver do Edge
      run: |
        wget https://msedgedriver.azureedge.net/LATEST_RELEASE -O latest_release.txt
        EDGE_VERSION=$(cat latest_release.txt)
        wget https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip -d /usr/local/bin
        chmod +x /usr/local/bin/msedgedriver

    - name: Verificar WebDriver
      run: |
        ls -l /usr/local/bin/msedgedriver
        /usr/local/bin/msedgedriver --version

    - name: Executar scripts
      env:
        EMAIL: ${{ secrets.MS_EMAIL }}
        PASSWORD: ${{ secrets.MS_PASSWORD }}
      run: python run_all_bots.py
